### ISSUE TITLE
USER STORY: Submitting an opinion poll

### ISSUE THREAD

**Issue by s-batish** [s-batish/love-running#1]
As a **user** I can **select and submit an answer from a poll** so that **I can provide my opinion with regards to a certain running topic**

# Acceptance Criteria:
- The answers should be in the form of checkboxes
- There should be a range of answers to choose from

#Tasks:
- [ ] Update the view: the poll design (HTML and CSS) to include the checkboxes
- [ ] Create at lease 5 answer options
- [ ] Test the functionality
